import monkdata as m
from dtree import averageGain
from varname import nameof


print("Monk1")
A1 = averageGain(m.monk1, m.attributes[0])
A2 = averageGain(m.monk1, m.attributes[1])
A3 = averageGain(m.monk1, m.attributes[2])
A4 = averageGain(m.monk1, m.attributes[3])
A5 = averageGain(m.monk1, m.attributes[4])
A6 = averageGain(m.monk1, m.attributes[5])
print("Information Gain A1 :",A1)
print("Information Gain A2 :",A2)
print("Information Gain A3 :",A3)
print("Information Gain A4 :",A4)
print("Information Gain A5 :",A5)
print("Information Gain A6 :",A6)
L = [(A1),(A2),(A3),(A4),(A5),(A6)]
L.sort()
print("Attribute to be used to split the exapmles at the root node :", L[5])

print("Monk2")
A1 = averageGain(m.monk2, m.attributes[0])
A2 = averageGain(m.monk2, m.attributes[1])
A3 = averageGain(m.monk2, m.attributes[2])
A4 = averageGain(m.monk2, m.attributes[3])
A5 = averageGain(m.monk2, m.attributes[4])
A6 = averageGain(m.monk2, m.attributes[5])
print("Information Gain A1 :",A1)
print("Information Gain A2 :",A2)
print("Information Gain A3 :",A3)
print("Information Gain A4 :",A4)
print("Information Gain A5 :",A5)
print("Information Gain A6 :",A6)
L = [(A1),(A2),(A3),(A4),(A5),(A6)]
L.sort()
print("Attribute to be used to split the exapmles at the root node :", L[5])
print("Monk3")
A1 = averageGain(m.monk3, m.attributes[0])
A2 = averageGain(m.monk3, m.attributes[1])
A3 = averageGain(m.monk3, m.attributes[2])
A4 = averageGain(m.monk3, m.attributes[3])
A5 = averageGain(m.monk3, m.attributes[4])
A6 = averageGain(m.monk3, m.attributes[5])
print("Information Gain A1 :",A1)
print("Information Gain A2 :",A2)
print("Information Gain A3 :",A3)
print("Information Gain A4 :",A4)
print("Information Gain A5 :",A5)
print("Information Gain A6 :",A6)
L = [(A1),(A2),(A3),(A4),(A5),(A6)]
L.sort()
print("Attribute to be used to split the exapmles at the root node :", L[5])